version: '3.3'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  rails:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: script/server


volumes:
  db:
